version: "3"

services:
  maria-db:
    container_name: database
    image: mariadb:10.7
    init:
      true
    ports:
      - 4306:3306
    # env_file:
    #   - .env
    environment:
      - TZ=UTC
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      - MYSQL_DATABASE=spacemap_db
    restart: always
    volumes:
      - C:/volume_db/mariadb/data:/var/lib/mysql
      - C:/volume_db/mariadb/conf.d:/etc/mysql/conf.d
      - C:/volume_db/mariadb/sql:/docker-entrypoint-initdb.d 
    networks:
      - spacenetwork
      
  spacemap_server:
    container_name: server
    image: jiminu/spacemap_server
    init:
      true
    # build: .
    depends_on:
      - maria-db
    restart: always
    ports:
      - 4003:3003
    command: tail -f /dev/null
    networks:
      - spacenetwork
    
networks:
  spacenetwork:
    driver: bridge