FROM mariadb:10.7

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV LC_ALL=C.UTF-8

ENV MYSQL_USER=root
# ENV MYSQL_DATABASE=test
ENV MYSQL_ROOT_PASSWORD=test

# EXPOSE 3306

COPY ./initfile.sql /docker-entrypoint-initdb.d/

# essential install
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update \ 
    && apt-get install -y \
    git \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    wget \
    vim \
    net-tools \
    psmisc

# install oh my zsh
RUN apt install -y zsh
RUN chsh -s /bin/zsh
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
RUN perl -pi -w -e "s/plugins=.*/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/g;" ~/.zshrc
RUN echo 'LS_COLORS="ow=01;36;40" && export LS_COLORS' >> ~/.zshrc

# install powerlevel10k (oh my zsh theme)
RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
RUN perl -pi -w -e 's/ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/g;' ~/.zshrc 
RUN echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc
RUN mkdir -p root/.vscode-server/data/Machine
RUN touch root/.vscode-server/data/Machine/settings.json
RUN echo '{"editor.fontFamily": "Consolas, 'Courier New', monospace, 'MesloLGS NF'",}' >> root/.vscode-server/data/Machine/settings.json
COPY ./.p10k.zsh /root/.p10k.zsh
RUN perl -pi -w -e 's/# If you come.*/if [[ -r "\${XDG_CACHE_HOME:-\$HOME\/.cache}\/p10k-instant-prompt-\${(%):-%n}.zsh" ]]; then\n  source "\${XDG_CACHE_HOME:-\$HOME\/.cache}\/p10k-instant-prompt-\${(%):-%n}.zsh"\nfi/g' ~/.zshrc

# RUN service mysql restart

# RUN mysql -u root -p

CMD tail -f /dev/null