version: "3"

services:
  maria-db:
    container_name: database
    image: mariadb:10.7
    ports:
      - 3306:3306
    # env_file:
    #   - .env
    environment:
      - MYSQL_ROOT_PASSWORD=passtest
      - MYSQL_DATABASE=testdb2
      - MYSQL_USER=t
      - MYSQL_PASSWORD=passtest
      - TZ=Asia/Seoul
    volumes:
      - C:/volume_db/mariadb/data:/var/lib/mysql
      - C:/volume_db/mariadb/conf.d:/etc/mysql/conf.d
    networks:
      - spacenetwork
      
  spacemap_server:
    container_name: server
    # image: jiminu/servertest
    build: .
    depends_on:
      - maria-db
    ports:
      - 3003:3003
    command: tail -f /dev/null
    networks:
      - spacenetwork
    
networks:
  spacenetwork:
    driver: bridge